// Generated by https://quicktype.io

export interface Spacex {
    flight_number:           number;
    mission_name:            string;
    mission_id:              string[];
    launch_year:             string;
    launch_date_unix:        number;
    launch_date_utc:         string;
    launch_date_local:       string;
    is_tentative:            boolean;
    tentative_max_precision: string;
    tbd:                     boolean;
    launch_window:           null;
    rocket:                  Rocket;
    ships:                   any[];
    telemetry:               Telemetry;
    launch_site:             LaunchSite;
    launch_success:          null;
    links:                   Links;
    details:                 string;
    upcoming:                boolean;
    static_fire_date_utc:    null;
    static_fire_date_unix:   null;
    timeline:                null;
    crew:                    null;
}

export interface LaunchSite {
    site_id:        string;
    site_name:      string;
    site_name_long: string;
}

export interface Links {
    mission_patch:       null;
    mission_patch_small: null;
    reddit_campaign:     string;
    reddit_launch:       null;
    reddit_recovery:     null;
    reddit_media:        null;
    presskit:            null;
    article_link:        null;
    wikipedia:           null;
    video_link:          null;
    youtube_id:          null;
    flickr_images:       any[];
}

export interface Rocket {
    rocket_id:    string;
    rocket_name:  string;
    rocket_type:  string;
    first_stage:  FirstStage;
    second_stage: SecondStage;
    fairings:     null;
}

export interface FirstStage {
    cores: Core[];
}

export interface Core {
    core_serial:     string;
    flight:          number;
    block:           number;
    gridfins:        boolean;
    legs:            boolean;
    reused:          boolean;
    land_success:    null;
    landing_intent:  boolean;
    landing_type:    string;
    landing_vehicle: string;
}

export interface SecondStage {
    block:    number;
    payloads: Payload[];
}

export interface Payload {
    payload_id:        string;
    norad_id:          any[];
    cap_serial:        null;
    reused:            boolean;
    customers:         string[];
    nationality:       string;
    manufacturer:      string;
    payload_type:      string;
    payload_mass_kg:   null;
    payload_mass_lbs:  null;
    orbit:             string;
    orbit_params:      { [key: string]: null | string };
    mass_returned_kg:  null;
    mass_returned_lbs: null;
    flight_time_sec:   null;
    cargo_manifest:    null;
}

export interface Telemetry {
    flight_club: null;
}
